FROM zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/rust:1.62.1 as planner
WORKDIR /app
COPY . .
RUN cargo build --release --bin helper

FROM zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/debian:buster-slim as runtime
COPY --from=builder /app/target/release/helper /usr/local/bin
RUN apt-get update && apt install -y openssl && apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

CMD ["helper"]
