apiVersion: v1
kind: ConfigMap
metadata:
  name: serviceportconfig
  namespace: {{ .Values.global.namespace.name | default .Release.Namespace  }}
data:
  IGNORE_PROJECTS: {{ .Values.environment.IGNORE_PROJECTS | quote }}