# Default values for layer3_token_storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: zivgitlab.wwu.io
  repository: sciebo-rds/sciebo-rds/port_openscienceframework
  tag: release
  pullPolicy: Always

labels:
  app.kubernetes.io/component: research-data-services.org
  app.kubernetes.io/part-of: connector
  research-data-services.org/layer: layer1

fullnameOverride: layer1-port-openscienceframework

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
    prometheus.io/scrape: "true"

domain: localhost
ingress:
  tls:
    secretName: sciebords-tls-public

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment:
  ADDRESS: https://accounts.test.osf.io
  API_ADDRESS: https://api.test.osf.io/v2
  OAUTH_CLIENT_ID: ""
  OAUTH_CLIENT_SECRET: ""
