apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circle3_token_storage.fullname" . }}
  labels:
{{ include "circle3_token_storage.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "circle3_token_storage.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "circle3_token_storage.labels" . | indent 8 }}
    spec:
      initContainers:
        - name: deploy
          image: redis
          command: [ "sh" ]
          args: [ "-c", 'while [ "$(redis-cli -h $REDIS_PORT_6379_TCP_ADDR ping)" != "PONG" ]; do sleep 2; done' ]
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REDIS_HOST
            value: {{ .Values.global.REDIS_HOST | quote }}
          - name: REDIS_PORT
            value: {{ .Values.global.REDIS_PORT | quote }}
          - name: REDIS_HELPER_HOST
            value: {{ .Values.global.REDIS_HELPER_HOST | quote }}
          - name: REDIS_HELPER_PORT
            value: {{ .Values.global.REDIS_HELPER_PORT | quote }}
          - name: use_inmemory_as_fallover
            value: {{ .Values.environment.IN_MEMORY_AS_FAILOVER | quote }}
          - name: REDIS_CHANNEL
            value: {{ .Values.global.REDIS_CHANNEL | quote }}
          envFrom:
          - configMapRef:
              name: proxy
          - configMapRef:
              name: globalenvvar
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
