apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circle1_port_datasafe.fullname" . }}
  labels:
{{ include "circle1_port_datasafe.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "circle1_port_datasafe.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "circle1_port_datasafe.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "DATASAFE_ADDRESS"
            value: "{{ .Values.environment.ADDRESS }}"
          - name: "OWNCLOUD_INSTALLATION_PATH"
            value: "{{ .Values.environment.OWNCLOUD_INSTALLATION_PATH }}"
          - name: "DATASAFE_PUBLICKEY"
            valueFrom:
              secretKeyRef:
                name: datasafe-keys
                key: publicKey.pem
          - name: "DATASAFE_PRIVATEKEY"
            valueFrom:
              secretKeyRef:
                name: datasafe-keys
                key: privateKey.pem
          envFrom:
          - configMapRef:
              name: mservice
          - configMapRef:
              name: proxy
          - configMapRef:
              name: globalenvvar
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
