apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  name: {{ include "layer0_web.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "layer0_web.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "layer0_web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
