FROM python:3.7-alpine
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN apk update && apk add build-base

WORKDIR /app
ARG CACHEINSTALLBUST=1
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

# download yaml file for better usability and reproducable behaviour
RUN apk add curl

ENV OPENAPI_FILEPATH_EXTERNAL   "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/master/RDS/circle2_use_cases/port_zenodo_openapi.yaml"
ENV OPENAPI_FILEPATH            "circle2.yaml"

ARG CACHEBUST=1
RUN curl -X GET "$OPENAPI_FILEPATH_EXTERNAL" -o "$OPENAPI_FILEPATH"

# now add everything else, which changes often
ADD . ./

ENTRYPOINT [ "python", "server.py" ]