apiVersion: v1
appVersion: "1.0"
description: The storage for tokens and passwords for services.
name: layer3-token-storage
version: 0.2.9
home: https://www.research-data-services.org/
keywords:
- research
- data
- services
- zenodo
maintainers:
- email: peter.heiss@uni-muenster.de
  name: Heiss
sources:
- https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: common
    version: ^0.1.0
    repository: file://../common