.central_service_research_manager:
  variables:
    FOLDER: RDS/layer3_central_services/research_manager

.tests_central_service_research_manager:
  extends:
    - .tests
    - .central_service_research_manager

test:central_service_research_manager:
  extends: .tests_central_service_research_manager

build:central_service_research_manager:
  needs:
    - test:central_service_research_manager
  extends:
    - .builds
    - .central_service_research_manager

  only:
    changes:
      - RDS/layer3_central_services/research_manager/*
      - RDS/layer3_central_services/research_manager/**/*

doc:central_service_research_manager:
  needs:
    - build:central_service_research_manager
  extends:
    - .documentation
    - .central_service_research_manager
