ARG IMAGE_PREFIX="zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/"

FROM ${IMAGE_PREFIX}python:3.9
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN pip install --upgrade pip setuptools wheel

WORKDIR /app
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

ARG git_branch=release
ADD "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/$git_branch/RDS/layer3_central_services/research_manager/central-service_research-manager.yml" ./

# now add everything else, which changes often
ADD src ./

ENTRYPOINT [ "python", "server.py" ]
