---
debug:
  addr: 0.0.0.0:9134
  token:
  pprof: false
  zpages: false

http:
  addr: 0.0.0.0:9130
  root: /

tracing:
  enabled: false
  type: jaeger
  endpoint: localhost:6831
  collector: http://localhost:14268/api/traces
  service: idp

...
