version: "3.8"

networks:
  default:
    external:
      name: describo-online_default

volumes:
    database_volume:
        driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: /postgresql/data
        volumes:
            - database_volume:/postgresql

    api:
        image: arkisto/describo-online-api:latest
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "admin"
            DB_PASSWORD: "admin"
            DB_DATABASE: "describo"
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
        volumes:
            - $PWD/production-configuration.json:/srv/configuration.json

    ui:
        image: arkisto/describo-online-ui:latest
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
        volumes:
            - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80