---
_extends: gh-labels

repository:
  name: ocis
  description: ':atom_symbol: ownCloud Infinite Scale Stack'
  homepage: https://owncloud.dev/ocis/
  topics: reva, ocis

  private: false
  has_issues: true
  has_projects: false
  has_wiki: true
  has_downloads: false

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: OCIS-Fastlane
    color: "#deadbf"
    description: Planned outside of the sprint
  
teams:
  - name: ci
    permission: admin
  - name: employees
    permission: push
  - name: cern
    permission: triage

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: false
        contexts:
          - continuous-integration/drone/pr
      enforce_admins: null
      restrictions:
        apps: []
        users: []
        teams:
          - ci
          - employees

...

