apiVersion: v1
kind: Namespace
metadata:
  name: research-data-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: globalenvvar
data:
  LOGLEVEL: DEBUG
  RDS_OAUTH_REDIRECT_URI: https://localhost/owncloud/index.php/apps/rds/oauth
  VERIFY_SSL: "True"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
data:
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: ""
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""