# Options: https://github.com/jaegertracing/helm-charts

ingress:
  enabled: true
  
  hosts:
    - host: sciebords-dev.org
      paths:
      - /tracing

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

cassandra:
  config:
    max_heap_size: 1024M 
    heap_new_size: 256M
  resources:
    requests:
      memory: 2048Mi
      cpu: 0.4
    limits:
      memory: 2048Mi
      cpu: 0.4

schema:
  activeDeadlineSeconds: 600
