.port_openscienceframework:
  variables:
    OPENSCIENCEFRAMEWORK_API_KEY: $GITLAB_OPENSCIENCEFRAMEWORK_API_KEY
    FOLDER: RDS/circle1_adapters_and_ports/port_openscienceframework

.tests_port_openscienceframework:
  extends:
    - .tests
    - .port_openscienceframework

test:port_openscienceframework:
  extends: .tests_port_openscienceframework

build:port_openscienceframework:
  extends:
    - .builds
    - .port_openscienceframework

  only:
    changes:
      - RDS/circle1_adapters_and_ports/port_openscienceframework/*
      - RDS/circle1_adapters_and_ports/port_openscienceframework/**/*
      - RDS/circle2_use_cases/interface_port_metadata.yml
      - RDS/circle3_central_services/interface_port_token_storage.yml

doc:port_openscienceframework:
  extends:
    - .documentation
    - .port_openscienceframework
