{{- if and .Values.collector.enabled .Values.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.collector.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.name | default .Release.Namespace  }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
{{- end -}}
