{{- if and .Values.ingester.enabled .Values.ingester.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.ingester.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.name | default .Release.Namespace  }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingester
{{- end -}}
