{{- if and .Values.query.enabled .Values.query.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.query.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace.name | default .Release.Namespace  }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
{{- end -}}
