---
debug:
  addr: 0.0.0.0:9109
  token:
  pprof: false
  zpages: false

http:
  addr: 0.0.0.0:9105

grpc:
  addr: 0.0.0.0:9106

tracing:
  enabled: false
  type: jaeger
  endpoint: localhost:6831
  collector: http://localhost:14268/api/traces
  service: reva

asset:
  path:

...
