FROM python:3.6-alpine
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN apk update && apk add --no-cache --virtual .build-deps build-base g++ python3-dev libffi-dev openssl-dev

WORKDIR /app
ADD ./requirements.txt ./
ADD ./datacite_4.3_schema.json ./
RUN pip install -r requirements.txt

ADD "../../circle2_use_cases/metadata/use-case_metadata.yml" ./

# now add everything else, which changes often
ADD src ./

ENTRYPOINT [ "python", "server.py" ]
