openapi: 3.0.0
paths:
  /jsonschema:
    get:
      summary: Get jsonschema
      tags: []
      responses:
        '200':
          description: 'Responds with the jsonschema of datacite kernel 4.3 '
          content:
            application/json:
              schema:
                type: object
                properties:
                  kernelversion:
                    type: string
                  schema:
                    type: string
      operationId: ''
      description: |-
        Returns the used jsonschema.
        Currently this is datacite kernel 4.3

        https://raw.githubusercontent.com/datacite/schema/master/source/json/kernel-4.3/datacite_4.3_schema.json
  '/user/{user-id}/research/{research-index}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: research-index
        in: path
        required: true
    get:
      summary: Get all metadata and corresponding research id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  researchId:
                    type: integer
                  length:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        port:
                          type: string
                        metadata:
                          type: object
              examples:
                example-1:
                  value:
                    length: 1
                    projectId: 5
                    list:
                      - - port: port-zenodo
                          metadata:
                            titles:
                              - title: long title
                                lang: en
                            publisher: research publisher gmbh
                            type:
                              resourceType: ''
                              resourceTypeGeneral: Poster
      operationId: api.UserResearch.get
      description: This endpoint returns the projectId for the given user and the index of project. This is an endpoint for convenience.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                - type: 'null'
            examples:
              example-1:
                value:
                  titles: ''
                  publisher: ''
                  type: ''
    patch:
      summary: Modify a research
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: 'This will returns only the updated fields, because this service redirects only the output from ports.'
                properties:
                  length:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
              examples:
                example-1:
                  value:
                    - port: port-zenodo
                      metadata:
                        titles:
                          - title: long title
                            lang: en
                        publisher: research publisher gmbh
                        type:
                          resourceType: ''
                          resourceTypeGeneral: Poster
  '/research/{research-id}':
    parameters:
      - schema:
          type: string
        name: research-id
        in: path
        required: true
    get:
      summary: Get all metadata from given research
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  length:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        port:
                          type: string
                        metadata:
                          type: object
              examples:
                example-1:
                  value:
                    length: 1
                    list:
                      - - port: port-zenodo
                          metadata:
                            titles:
                              - title: long title
                                lang: en
                            publisher: research publisher gmbh
                            type:
                              resourceType: ''
                              resourceTypeGeneral: Poster
      operationId: ''
      description: "Take a look at the datacite specification (https://raw.githubusercontent.com/datacite/schema/master/source/json/kernel-4.3/datacite_4.3_schema.json) for all useable keywords. \n\nSee the examples to see, how to use it."
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                - type: 'null'
            examples:
              example-1:
                value:
                  titles: ''
                  publisher: ''
                  type: ''
        description: 'If no keys are given, it returns all metadata.'
    patch:
      summary: Modify a research
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: 'This will returns only the updated fields, because this service redirects only the output from ports.'
                properties:
                  length:
                    type: integer
                  list:
                    type: array
                    items:
                      type: object
              examples:
                example-1:
                  value:
                    - port: port-zenodo
                      metadata:
                        titles:
                          - title: long title
                            lang: en
                        publisher: research publisher gmbh
                        type:
                          resourceType: ''
                          resourceTypeGeneral: Poster
      requestBody:
        description: The given body has to be valid against the datacite jsonschema (without required fields).
        content:
          application/json:
            schema:
              type: object
            examples:
              example-1:
                value:
                  titles:
                    - title: long title
                      lang: en
                  publisher: research publisher gmbh
                  type:
                    resourceType: ''
                    resourceTypeGeneral: Poster
      description: "Take a look at the datacite specification (https://raw.githubusercontent.com/datacite/schema/master/source/json/kernel-4.3/datacite_4.3_schema.json) for all useable keywords. \n\nSee the examples to see, how to use it."
info:
  version: '1.0'
  title: Metadata Service
  description: This service is responsible for any metadata functionality to get and update all metadata through the ports. This is a convenient way to interact with the metadata from the ports.
  contact:
    name: Peter Heiss
    url: 'https://www.research-data-services.org'
    email: peter.heiss@uni-muenster.de
servers:
  - url: 'http://use-case_metadata:3000/metadata'
    description: ''
components:
  schemas: {}
