apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: layer2-metadata-service
version: 0.2.3
home: https://www.research-data-services.org/
keywords:
- research
- data
- services
- zenodo
maintainers:
- email: peter.heiss@uni-muenster.de
  name: Heiss
sources:
- https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: common
    version: ^0.1.0
    repository: file://../common