FROM https://zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/python:3.8-alpine
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN apk update && apk add --no-cache --virtual .build-deps build-base g++ python3-dev libffi-dev openssl-dev

WORKDIR /app
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

ADD "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/informations-ep/RDS/circle3_central_services/token_storage/central-service_token-storage.yml" ./

# now add everything else, which changes often
ADD src ./

ENTRYPOINT [ "python", "server.py" ]
