.port_owncloud:
    variables:
        ZENODO_API_KEY: $GITLAB_ZENODO_API_KEY
        FOLDER: RDS/circle1_adapters_and_ports/port_owncloud

.tests_port_owncloud:
    extends:
        - .tests
        - .port_owncloud

test:port_owncloud:
    extends: .tests_port_owncloud

build:port_owncloud:
    needs:
        - test:port_owncloud
    extends:
        - .builds
        - .port_owncloud

    only:
        changes:
            - RDS/circle1_adapters_and_ports/port_owncloud/*
            - RDS/circle1_adapters_and_ports/port_owncloud/**/*
            - RDS/circle2_use_cases/interface_port_file_storage.yml
            - RDS/circle3_central_services/interface_port_token_storage.yml

doc:port_owncloud:
    needs:
        - build:port_owncloud
    extends:
        - .documentation
        - .port_owncloud
