FROM zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/python:3.8
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN pip install --upgrade pip setuptools wheel

WORKDIR /app
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

ARG git_branch=release
ADD "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/$git_branch/RDS/layer2_use_cases/exporter/use-case_exporter.yml" ./

# now add everything else, which changes often
ADD src ./

ENTRYPOINT [ "python", "server.py" ]
