FROM python:3.6-alpine
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN apk update && apk add --no-cache --virtual .build-deps build-base g++ python3-dev libffi-dev openssl-dev

WORKDIR /app
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

ENV CENTRAL-SERVICE_TOKEN-STORAGE "http://circle3-token-storage"

ADD "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/connnectUI/RDS/circle2_use_cases/port/use-case_token-storage.yml" ./

# now add everything else, which changes often
ADD src ./

ENTRYPOINT [ "python", "server.py" ]
