.port_zenodo:
  variables:
    ZENODO_API_KEY: $GITLAB_ZENODO_API_KEY
    FOLDER: RDS/layer1_adapters_and_ports/port_zenodo

.tests_port_zenodo:
  extends:
    - .tests
    - .port_zenodo

test:port_zenodo:
  extends: .tests_port_zenodo

build:port_zenodo:
  needs:
    - test:port_zenodo
  extends:
    - .builds
    - .port_zenodo

  only:
    changes:
      - RDS/layer1_adapters_and_ports/port_zenodo/*
      - RDS/layer1_adapters_and_ports/port_zenodo/**/*
      - RDS/layer2_use_cases/interface_port_metadata.yml
      - RDS/layer3_central_services/interface_port_token_storage.yml

doc:port_zenodo:
  needs:
    - build:port_zenodo
  extends:
    - .documentation
    - .port_zenodo
