FROM python:3.7-alpine
EXPOSE 8080

# set the base installation, requirements are not changed often
RUN apk update && apk add build-base

WORKDIR /app
ADD ./requirements.txt ./
RUN pip install -r requirements.txt

# download yaml file for better usability and reproducable behaviour
RUN apk add curl

ENV OPENAPI_FILEPATH_EXTERNAL   "https://raw.githubusercontent.com/Sciebo-RDS/Sciebo-RDS/master/RDS/circle3_central_services/token_service/central-service_token-storage.yml"
ENV OPENAPI_FILEPATH            "token_service.yml"
RUN curl -X GET "$OPENAPI_FILEPATH_EXTERNAL" -o "$OPENAPI_FILEPATH"

# now add everything else, which changes often
ADD src/* ./

ENTRYPOINT [ "python", "server.py" ]
