.official_doc:
  variables:
    FOLDER: RDS/layer0_ingress/official_doc

build:official_doc:
  needs:
    - pages
  stage: pages
  cache:
    paths:
      - public
  extends:
    - .builds
    - .official_doc

  before_script:
    - cp -r public $FOLDER/public

  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: '$CI_COMMIT_BRANCH == "release"'
    - if: "$CI_COMMIT_TAG"
      variables:
        DOC_FOLDER: .