apiVersion: v1
appVersion: "1.0"
description: The project manager to manage projects within RDS
name: layer3-research-manager
version: 0.3.3
home: https://www.research-data-services.org/
keywords:
- research
- data
- services
- zenodo
maintainers:
- email: peter.heiss@uni-muenster.de
  name: Heiss
sources:
- https://www.research-data-services.org/
icon: https://www.research-data-services.org/img/sciebo.png
dependencies:
  - name: common
    version: ^0.1.0
    repository: file://../common